### PR TITLE
Typos and grammar update to ubuntu-focal-zfs.1.md

### PR DESCRIPTION
**Pull request by rhys-the-davies**
I only made some typo and grammatical changes. It reads really nice though, good job. I think this is the one we should duplicate and post on Ubuntu.com and then link to your sites for the rest. Once you have a publish date let me know and I'll schedule it for the Ubuntu blog. :)

### CODE REVIEW

**Comment by didrocks** [comment]
Excellent! Merging, thanks a lot! What do you think about publishing this one tomorrow afternoon then? (My goal is to publish on Thursday and Tuesday).

**Comment by rhys-the-davies** [comment]
Well, if you're posting this one on Thursday I think we should wait until Tuesday to post this one on Ubuntu so that we can link to part 2 right away. What do you think?

**Comment by didrocks** [comment]
Perfect! Let’s do this :)

**Comment by rhys-the-davies** [comment]
Great, I saved the post in Word Press, before I schedule it for Tuesday would you mind having a quick look, making sure I have all the images in the right places and recommend a featured image to appear as the thumbnail? https://admin.insights.ubuntu.com/wp-admin/post.php?post=95840&action=edit

Then we're done :)

**Comment by didrocks** [comment]
I can’t click on it to review this article (maybe because the Author is Didier Roche, where my account is linked to didrocks)?

**Comment by rhys-the-davies** [comment]
Ah, whoops, I changed it to didrocks, give it another go :)

**Comment by didrocks** [comment]
Thanks! I published it now: https://didrocks.fr/2020/05/21/zfs-focus-on-ubuntu-20.04-lts-whats-new/. At the same time, I updated the wordpress version to link to the discourse thread. The only difference with the main article is the lack of OpenZFS logo, but unsure this is needed. Otherwise, we are good :)

**Comment by rhys-the-davies** [comment]
Wonderful, as soon as you're done in the Wordpress version I'll add the OpenZFS logo, I think that makes sense, and schedule the article to go up on Tuesday linking to the second one when it drops :) Thanks for doing all of this :)

**Pull request merged**
